# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-22 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20190222_1101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermessage',
            options={'verbose_name': '用户留言信息', 'verbose_name_plural': '用户留言信息'},
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='message',
            field=models.CharField(max_length=500, null=True, verbose_name='留言信息'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='name',
            field=models.CharField(default='', max_length=20, verbose_name='用户名'),
        ),
    ]
